
[functions.tvl-check]
enabled = true
verify_jwt = false
import_map = "./functions/tvl-check/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/tvl-check/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/tvl-check/*.html" ]

[functions.inspect-tvl]
enabled = true
verify_jwt = false
import_map = "./functions/inspect-tvl/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/inspect-tvl/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/inspect-tvl/*.html" ]
